---
title: "xdeb.org"
baseURL: "http://xdeb-static.dev/"
theme: "zen"
languageCode: "en_GB"
defaultContentLanguage: "en"
metaDataFormat: "yaml"

params:
  copyright: "<!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->"
  contact: "info@xdeb.org"
  footer: "Powered by [Hugo](https://gohugo.io/). A [xdeb.net](https://xdeb.net/) production."
  jquery: true
  slicknav: true
