---
title: "xdeb.org"
baseURL: "https://xdeb.org/"
theme: "zen"
languageCode: "en-GB"
defaultContentLanguage: "en"
metaDataFormat: "yaml"
pluralizelisttitles: false
removePathAccents: true
paginate: 10
paginatePath: "page"
rssLimit: 20
author:
  name: "Fredrik Jonsson"
  url: "https://xdeb.org/fredrik"
  avatar: "site/fredrik.jpg"

permalinks:
  post: "/post/:year/:month/:day/:slug"

outputFormats:
  SearchIndex:
    mediaType: "application/json"
    baseName: "searchindex"
    isPlainText: true
    notAlternative: true

outputs:
  home: ["HTML","RSS", "JSON", "SearchIndex"]
  section: ["HTML","RSS", "JSON"]

params:
  cacheBustCSS: true
  cacheBustJS: false
  contact: "info@xdeb.org"
  copyright: "<!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->"
  dateformat: "2 January, 2006"
  favicon: "icon-64.png"
  feedlinks: true
  footer: "Powered by [Hugo](https://gohugo.io/). A [xdeb.net](https://xdeb.net/) production."
  frontposts: 3
  icon: "apple-touch-icon-180.png"
  imageMaxWidth: 400
  jquery: true
  logo: false
  poweredby: false
  search: false
  searchSize: 20
  sidebar: false
  slicknav: true
  submitted: true

menu:
  main:
      - Name: "Home"
        weight: -10
        URL: "/"
      - Name: "Posts"
        weight: -9
        URL: "/post/"
      - Name: "About"
        weight: 9
        URL: "/fredrik/"
      - Name: "Ragnvald"
        weight: 10
        URL: "/ragnvald/"
