---
title: "xdeb.org"
baseURL: "https://xdeb.org/"
theme:
  - "xdeb"
  - "zen"
languageCode: "en-GB"
defaultContentLanguage: "en"
metaDataFormat: "yaml"
pluralizelisttitles: false
removePathAccents: true
paginate: 10
paginatePath: "page"
rssLimit: 20
summaryLength: 40
newContentEditor: "/usr/local/bin/bbedit"
author:
  name: "Fredrik Jonsson"
  url: "https://xdeb.org/fredrik"
  avatar: "site/fredrik.jpg"

blackfriday:
  fractions: false

permalinks:
  post: "/post/:year/:month/:day/:slug"
  micro: "/micro/:year/:month/:day/:slug"

outputFormats:
  SearchIndex:
    mediaType: "application/json"
    baseName: "searchindex"
    isPlainText: true
    notAlternative: true

outputs:
  home: ["HTML","RSS", "JSON", "SearchIndex"]
  section: ["HTML","RSS", "JSON"]

params:
  cacheBustCSS: false
  cacheBustJS: false
  contact: "info@xdeb.org"
  copyright: "<!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->"
  description: "The blog of Fredrik Jonsson, web developer and Linux sysadmin."
  dateformat: "2 January, 2006"
  favicon: "icon-64.png"
  feedlinks: true
  footer: "Powered by [Hugo](https://gohugo.io/) and the [Zen theme](https://github.com/frjo/hugo-theme-zen). [xdeb.net hosting](https://xdeb.net/)"
  frontposts: 3
  icon: "apple-touch-icon-180.png"
  image: "xdeb-org.jpg"
  imageMaxWidth: 400
  jquery: true
  logo: false
  microUsername: "frjo"
  mobileMenu: true
  piwikSiteId: 1
  piwikTrackerUrl: "admin.combonet.se/matomo"
  poweredby: false
  search: false
  searchSize: 20
  sidebar: false
  submitted: true

menu:
  main:
    - Name: "Home"
      weight: -10
      URL: "/"
    - Name: "Posts"
      weight: -9
      URL: "/post/"
      identifier: "post"
    - Name: "Archive"
      weight: -8
      URL: "/#blog-archive"
      identifier: "archive"
    - Name: "Ragnvald"
      weight: 10
      URL: "/ragnvald/"
      identifier: "ragnvald"
    - Name: "Services"
      weight: 15
      URL: "https://xdeb.net/"
#     - Name: "Micro"
#       weight: -8
#       URL: "/micro/"
#       identifier: "micro"

